### ISSUE TITLE
Fix the admin buttons in admin console extending all the way to either side of the page

### ISSUE THREAD

**Issue by claytonmsafranek** [claytonmsafranek/UNO-CSLC-Ticket-Portal#112]
![image](https://github.com/claytonmsafranek/UNO-CSLC-Ticket-Portal/assets/99138388/7a8a8c45-bfb8-4f05-943f-e178918fe7d4)

**Comment by reyes256** [comment]
Hi, i would like to work on this issue.

**Comment by reyes256** [comment]
@claytonmsafranek hello, i just made a pull request about this issue, hope it helps.

FYI @Mr-Oregano
