### ISSUE TITLE
Investigate why MySQL starts on port 0

### ISSUE THREAD

**Issue by claytonmsafranek** [claytonmsafranek/UNO-CSLC-Ticket-Portal#27]

**Comment by Mr-Oregano** [comment]
https://stackoverflow.com/questions/60299450/2002-cant-connect-to-local-mysql-server-through-socket-var-run-mysqld-mysq
https://stackoverflow.com/questions/9979134/how-can-i-change-mysql-port-from-0-to-3306

**Comment by Mr-Oregano** [comment]
It's possible there wasn't enough memory on the VM when running RemoteSSH on vscode. Cannot replicate this when not using RemoteSSH.
